version: "3"

services:
  walletserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ../secrets:/usr/src/app/secrets:ro

  passthrough:
    build:
      context: .
      dockerfile: DockerfilePassthrough
    ports:
      - "3002:3002"
    volumes:
      - ../blockfrostApiKeys.json:/usr/src/app/blockfrostApiKeys.json:ro
